### PR TITLE
Fix password issue

### LINKED ISSUE #311: Can't use password if it contains quote symbol
In my recipe I take password from chef-vault to enable mariadb replication, but if fails when parsing SQL-expression because random-generated password contains the quote symbol ( ' ) and SQL syntax parser fails when trying to parse this:

MASTER_PASSWORD='3svd'P+w5ks-stdf\#srg0kk'

Is it normal behaviour for password parser, and what to do if password contains special characters like quotes?

### PR DESCRIPTION
**Pull request by TheREK3R**
## Description

This allows for the ' or " character in a password by escaping the character
It also fixes some testing errors

### Issues Resolved

https://github.com/sous-chefs/mariadb/issues/311

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/mariadb/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
> It seems as though the failures are being caused by this [issue](https://github.com/inspec/inspec/issues/5218) that I just filed. So I think we can ignore those for now. I'll test it locally for each platform to ensure it actually is passing properly.

I have submitted this change https://github.com/inspec/inspec/pull/5219 to fix this issue. In the meantime, I recommend you change all of the occurrences of ``stdout`` and ``stderr`` for the ``mysql_resource`` tests. In addition, you should comment out the ``exit_status`` checks with a ``TODO`` comment pointing to the PR I mentioned above until that gets merged/released.

File: test/integration/resources/controls/database_spec.rb [hunk 1]
```diff
@@ -5,7 +5,7 @@
   sql = mysql_session('root', 'gsql')
 
   describe sql.query('show databases') do
-    its('stdout') { should match(/databass/) }
-    its('stdout') { should_not match(/datatrout/) }
+    its('stderr') { should match(/databass/) }
```
Comment (ramereth) [inline test/integration/resources/controls/database_spec.rb]: These all should be the following
```suggestion
    its('output') { should match(/databass/) }
```

**Review by ramereth — DISMISSED** [review]

File: resources/server_install.rb [hunk 2]
```diff
@@ -51,7 +52,7 @@
   #                                             2- the user did not pass anything to the password argument OR
   #                                                the user did not define node['mariadb']['server_root_password'] attribute
   mariadb_root_password = (new_resource.password == 'generate' || new_resource.password.nil?) ? secure_random : new_resource.password
-
+  mariadb_root_password = mariadb_root_password.gsub('\\', '\\\\\\').gsub('\'', '\\\\\'').gsub('"', '\\\\"')
```
Comment (xorima) [inline resources/server_install.rb:57]: Can we get a comment on the line above explaining this, as it is pretty complex ...

File: resources/server_install.rb [hunk 3]
```diff
@@ -52,6 +52,8 @@
   #                                             2- the user did not pass anything to the password argument OR
   #                                                the user did not define node['mariadb']['server_root_password'] attribute
   mariadb_root_password = (new_resource.password == 'generate' || new_resource.password.nil?) ? secure_random : new_resource.password
+  
+  # Here we make sure to escape all \ ' and " charachters so that they will be preserved in the final password
```
Comment (ramereth) [inline resources/server_install.rb]:
```suggestion
  # Here we make sure to escape all \ ' and " characters so that they will be preserved in the final password
```

**Review by ramereth — APPROVED** [review]

File: resources/server_install.rb (hunk 3 above)
Comment (xorima) [inline resources/server_install.rb]:
```suggestion
  # Here we make sure to escape all \ ' and " characters so that they will be preserved in the final password
```
